In [ ]:
import numpy as np
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=300, centers=3, n_features=2, random_state=0)

In [64]:
weights_test = 0.01 * np.random.randn(2, 3)
weights_test

array([[-0.00513545,  0.0030232 ,  0.00246508],
       [ 0.0028174 ,  0.0109178 , -0.01076607]])

In [65]:
biases_test = np.zeros((1, 3))
biases_test

array([[0., 0., 0.]])

In [66]:
np.dot(2, ((2,4,1),(2,3,4)))

array([[4, 8, 2],
       [4, 6, 8]])

In [69]:
output_test = np.dot(2, weights_test) + biases_test
output_test

array([[-0.0102709 ,  0.00604641,  0.00493016],
       [ 0.00563479,  0.02183561, -0.02153215]])

In [2]:
class Layer_Dense():
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [81]:
dense = Layer_Dense(2, 3)
X = np.array([[1.0, 2.0]])
dense.forward(X)

print(f"Weights: {dense.weights}\n")
print(f"Biases: {dense.biases}\n")
print(f"X: {X}\n")
print(f"Output: {dense.output}")



Weights: [[-0.00943674 -0.00118279 -0.00720336]
 [-0.00902006 -0.00989759 -0.00411822]]

Biases: [[0. 0. 0.]]

X: [[1. 2.]]

Output: [[-0.02747685 -0.02097796 -0.0154398 ]]


In [3]:
class Activation_ReLU():
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [86]:
np.maximum(0, 10)

np.int64(10)

In [87]:
np.maximum(0, -10)

np.int64(0)

In [4]:
class Activation_Softmax():
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [98]:
np.exp(0)

np.float64(1.0)

In [97]:
np.exp(1000)

/var/folders/_2/_yhjp4h153l3658w2fh53v580000gn/T/ipykernel_38311/2006519253.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(1000)


np.float64(inf)

In [104]:
exp_vals = np.exp([[1.0 , 2.0]] - np.max([[1.0 , 2.0]], axis=1, keepdims=True))
exp_vals

array([[0.36787944, 1.        ]])

In [105]:
exp_vals / np.sum(exp_vals, axis=1, keepdims=True)

array([[0.26894142, 0.73105858]])

In [95]:
a = Activation_Softmax()
a.forward(dense.output)

a.output

array([[0.33127613, 0.33343606, 0.33528781]])

In [5]:
class Loss():
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [6]:
class Loss_CCE(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[
            range(samples),
            y_true
        ]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(
            y_pred_clipped*y_true,
            axis=1
        )
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

In [33]:
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()
loss_function = Loss_CCE()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])
loss = loss_function.calculate(activation2.output, y)
print('loss:', loss)

[[0.33358987 0.33345066 0.33295946]
 [0.33336713 0.33331861 0.33331425]
 [0.33357768 0.33344509 0.33297722]
 [0.33344646 0.33338509 0.33316845]
 [0.3333835  0.33335629 0.33326021]]
loss: 1.0985225334982138
