# A NEW APPROACH

In [35]:
import numpy as np
import matplotlib.pyplot as plt

### Coding a single Neuron

In [36]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

In [37]:
output = [inputs[0] * weights[0] +
          inputs[1] * weights[1] + 
          inputs[2] * weights[2] +
          inputs[3] * weights[3] +
          bias]

output

[4.8]

### Coding a layer of Neurons

In [38]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [39]:
outputs = [
    inputs[0] * weights1[0] +
    inputs[1] * weights1[1] + 
    inputs[2] * weights1[2] +
    inputs[3] * weights1[3] + bias1,

    inputs[0] * weights2[0] +
    inputs[1] * weights2[1] + 
    inputs[2] * weights2[2] +
    inputs[3] * weights2[3] + bias2,

    inputs[0] * weights3[0] +
    inputs[1] * weights3[1] + 
    inputs[2] * weights3[2] +
    inputs[3] * weights3[3] + bias3
]

outputs

[4.8, 1.21, 2.385]

In [40]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


### Vectors

In [41]:
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product

20

In [42]:
output = []

output=0
for x, y in zip(a, b):
    output += x*y
output

20

### Neurons with NumPy

In [43]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

In [44]:
outputs = np.dot(inputs, weights) + bias
outputs

np.float64(4.8)

In [46]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

outputs = np.dot(weights, inputs) + biases
outputs

array([4.8  , 1.21 , 2.385])

### Matrixes

In [47]:
a = [1, 2, 3]

print(np.array(a))

[1 2 3]


In [50]:
print(np.expand_dims(np.array(a), axis=0))

[[1 2 3]]


In [51]:
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a, b))

[[20]]
